apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dev-02
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/dev/dev-02
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-configs
  timeout: 1m0s
