apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  provider: gatewayapi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  service:
    port: 9898
    gatewayRefs:
      - name: gke-gateway
        namespace: flagger-system
  analysis:
    interval: 10m
    threshold: 2
    stepWeight: 10
    maxWeight: 50
