apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Points back to the raw manifests
resources:
  - ../../../base/podinfo

# This instructs kustomize to inject "podinfo" as the namespace
# for all resources imported from the base!
namespace: podinfo

labels:
  env: dev

annotations:
  tamir: washere
