apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/notifications
patches:
  - target:
      kind: Deployment
      name: notifications
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 1000
