apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../podinfo
namespace: dev-01
labels:
  - pairs:
      app.kubernetes.io/part-of: microservices-dev-fleet
      platform.fluxcd.io/environment: dev-01
      platform.fluxcd.io/environment-type: development


