apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../podinfo
  - frontend
  - catalog
  - orders
  - payments
  - notifications
namespace: dev-02
labels:
  - pairs:
      app.kubernetes.io/part-of: microservices-dev-fleet
      platform.fluxcd.io/environment: dev-02
      platform.fluxcd.io/environment-type: development


